Repository AIDASoft/DD4hep, pull requests merged in 2018-05, with the labels that each got.

#379 Fixed incorrect callback for Geant4FieldTrackingConstruction
  DDG4/plugins/Geant4FieldTrackingSetup.cpp
Labels: bug fix

#380 Update LICENSE to LGPLv3
  LICENCE
  LICENSE
  README.md
Labels: enhancement

#389 fix bug in input handling
  DDG4/src/Geant4InputHandling.cpp
  doc/ReleaseNotes.md
Labels: bug fix

#391 Remove duplicate ReleaseNotes.md entry
  doc/ReleaseNotes.md
Labels: cleanup
