Repository AIDASoft/DD4hep, pull requests merged in 2018-02, with the labels that each got.

#310 Fix problem in DDG4 MC truth handling
  DDCore/include/XML/DocumentHandler.h
  DDCore/include/XML/XML.h
  DDCore/include/XML/XMLElements.h
  DDCore/src/XML/DocumentHandler.cpp
  DDCore/src/XML/XMLElements.cpp
  DDCore/src/XML/tinyxmlparser_inl.h
  DDG4/include/DDG4/Geant4Particle.h
  DDG4/src/Geant4Particle.cpp
  DDG4/src/Geant4ParticleHandler.cpp
Labels: bug fix

#313 Add sequence for fallthrough to disable warning
  DDCore/src/XML/tinyxmlparser_inl.h
Labels: regression fix

#302 Added "NOINSTALL" option to cmake build function dd4hep_add_library
  cmake/DD4hepBuild.cmake
Labels: enhancement

#316 Fix bug in DDDBDetectorDumps logic
  DDDB/src/plugins/DDDBDetectorDumps.cpp
Labels: regression fix

#323 avoid usage of stringstream move for older compilers
  DDG4/src/Geant4InputHandling.cpp
Labels: regression fix
