Repository AIDASoft/DD4hep, pull requests merged in 2018-03, with the labels that each got.

#317 [WIP] DDCore: added CartesianStrip segmentations
  DDCore/include/DD4hep/CartesianStripX.h
  DDCore/include/DD4hep/CartesianStripY.h
  DDCore/include/DD4hep/CartesianStripZ.h
  DDCore/include/DDSegmentation/CartesianStrip.h
  DDCore/include/DDSegmentation/CartesianStripX.h
  DDCore/include/DDSegmentation/CartesianStripY.h
  DDCore/include/DDSegmentation/CartesianStripZ.h
  DDCore/src/CartesianStripX.cpp
  DDCore/src/CartesianStripY.cpp
  DDCore/src/CartesianStripZ.cpp
  DDCore/src/SegmentationDictionary.h
  DDCore/src/Segmentations.cpp
  DDCore/src/plugins/ReadoutSegmentations.cpp
  DDCore/src/segmentations/CartesianStrip.cpp
  DDCore/src/segmentations/CartesianStripX.cpp
  DDCore/src/segmentations/CartesianStripY.cpp
  DDCore/src/segmentations/CartesianStripZ.cpp
Labels: enhancement

#322 Fix multipole fields
  DDCore/include/DD4hep/FieldTypes.h
  DDCore/src/FieldTypes.cpp
Labels: bug fix

#319 Remove unnecessary import exceptions
  DDG4/python/DD4hep.py
  DDG4/python/DDG4.py
Labels: regression fix

#333 graphicalMaterialScan: add electric and magnetic fields scans
  UtilityApps/CMakeLists.txt
  UtilityApps/src/graphicalMaterialScan.cpp
  UtilityApps/src/graphicalScan.cpp
Labels: enhancement

#343 Use magFromXYZ instead of radiusFromXYZ to calculate Pseudorapidity
  DDCore/include/DDSegmentation/SegmentationUtil.h
Labels: bug fix

#341 Remove DDSegmentation folder as it was merged into DDCore
  CMakeLists.txt
  DDSegmentation/CMakeLists.txt
  DDSegmentation/cmake/DDSegmentationConfig.cmake.in
  DDSegmentation/src/bla.cpp
Labels: cleanup
