Repository AIDASoft/DD4hep, pull requests merged in 2019-10, with the labels that each got.

#568 fix conversion unicode to str
  DDG4/python/DDG4.py
Labels: bug fix

#574 CMake: When needing boost::filesystem we need at least 1.56
  cmake/DD4hepBuild.cmake
Labels: bug fix

#586 remove deprecated rootcling flags
  cmake/DD4hepBuild.cmake
Labels: cleanup

#592 Fix AClick Tests (fixes #591)
  DDG4/examples/initAClick.C
  examples/LHeD/scripts/initAClick.C
Labels: regression fix
