Repository AIDASoft/DD4hep, pull requests merged in 2020-09, with the labels that each got.

#699 Set search order for python on macOS to search for system python last
  CMakeLists.txt
Labels: bug fix

#701 update CI and build all files and show all errors
  .gitlab-ci.yml
Labels: cleanup

#702 Add starttheta,endtheta,endphi xml accessors. Fix sphere shape creator
  DDCore/include/Parsers/detail/Dimension.h
  DDCore/include/Parsers/detail/Dimension.imp
  DDCore/include/XML/UnicodeValues.h
  DDCore/src/plugins/ShapePlugins.cpp
  examples/ClientTests/compact/Check_Shape_Sphere.xml
  examples/ClientTests/ref/Ref_Sphere.txt
Labels: Fixed, bug fix, enhancement

#718 Replace deprecated PyOS_AfterFork for python 3.7 and above
  DDG4/tpython/DDPython.cpp
Labels: cleanup
