Repository AIDASoft/DD4hep, pull requests merged in 2020-11, with the labels that each got.

#725 [CMAKE]: fail if dd4hep and root python do not match
  .github/scripts/compile_and_test.sh
  CMakeLists.txt
  cmake/DD4hepBuild.cmake
  cmake/DD4hepConfig.cmake.in
Labels: regression fix

#731 Tests: use RESOURCE_LOCK to ensure tests are not running concurrently
  examples/LHeD/CMakeLists.txt
Labels: bug fix

#749 Add section about units to manual
  doc/usermanuals/DD4hep/chapters/basics.tex
Labels: enhancement

#752 Test XERCESC in CI
  .github/scripts/compile_and_test.sh
  .github/workflows/mac.yml
Labels: regression fix

#751 Resolve which type of linker is used and assign proper linking flags
  cmake/DD4hepBuild.cmake
Labels: bug fix
