Repository AIDASoft/DD4hep, pull requests merged in 2021-03, with the labels that each got.

#792 Solve problem with lib suffix and define BUILD_BYPRODUCTS for ninja
  DDCAD/CMakeLists.txt
Labels: bug fix

#788 For GNU linker only needed libs
  cmake/DD4hepBuild.cmake
Labels: cleanup

#791 Another Coverity battle
  DDCond/src/ConditionsRepository.cpp
  DDCond/src/Type1/Manager_Type1.cpp
  DDCore/include/DD4hep/DetectorImp.h
  DDCore/include/DD4hep/Handle.h
  DDCore/src/DetectorImp.cpp
  DDCore/src/Plugins.cpp
  DDG4/include/DDG4/Geant4Action.h
  DDG4/include/DDG4/Geant4Handle.h
  DDG4/plugins/Geant4DetectorGeometryConstruction.cpp
  DDG4/plugins/Geant4EventReaderHepMC.cpp
  DDG4/src/Geant4Handle.cpp
Labels: bug fix

#795 Geant4InputHandling: add debug printout for particle selection/rejection
  DDG4/src/Geant4InputHandling.cpp
Labels: cleanup

#796 RootDictionary: qualify std::pair, using namespace std was dropped fr…
  DDCore/src/RootDictionary.h
Labels: bug fix, cleanup

#799 Geant4: flush the buffer to fix the problem with the garbage output a…
  DDG4/src/Geant4Kernel.cpp
Labels: bug fix

#793 Add special treatment for full tube to Tube creator
  DDCore/src/Shapes.cpp
Labels: bug fix
